version: "3.8"
services:
  nginx:
    image: nginx:stable
    environment:
      APPLICATION_PORT: ${APPLICATION_PORT:-3000}
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./localhost.pokutuna.com.nginx.conf:/template.conf:ro
      - ~/Dropbox/certbot/config/:/etc/letsencrypt/:ro
    command: >
      /bin/bash -c "envsubst '$$APPLICATION_PORT' < /template.conf > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
